// export const Images = {
//   meatFish: require('../assets/images/Meat&Fish.png'),
//   shop: require('../assets/images/Shop.png'),
//   explore: require('../assets/images/Explore.png'),
//   cart: require('../assets/images/Cart.png'),
//   favourite: require('../assets/images/favourite1.png'),
//   user: require('../assets/images/user1.png'),
//   vector: require('../assets/images/Vector.png'),
//   vectorSend: require('../assets/images/Vector-Send.png'),
//   vectorLike: require('../assets/images/Vector-Like.png'),
//   vectorDown: require('../assets/images/Vector-Down.png'),
//   vectorRight: require('../assets/images/Vector-Right.png'),
//   rating: require('../assets/images/Rating.png'),
//   fruitsVeg: require('../assets/images/Fruits&veg.png'),
//   cookingOil: require('../assets/images/Cookingoil.png'),
//   bakerySnack: require('../assets/images/Backery&Snack.png'),
//   dairyEggs: require('../assets/images/Dairy&Eggs.png'),
//   beverages: require('../assets/images/Beverages.png'),
//   vectorSearch: require('../assets/images/Vector-Search.png'),
//   banner1: require('../assets/images/Banner1.jpg'),
//   banner2: require('../assets/images/Banner2.jpg'),
//   banner3: require('../assets/images/Banner3.jpg'),
//   fruite1: require('../assets/images/Fruite1.jpg'),
//   fruite2: require('../assets/images/Fruite2.jpg'),
//   fruite3: require('../assets/images/Fruite3.jpg'),
//   fruite4: require('../assets/images/Fruite4.jpg'),
//   fruite5: require('../assets/images/Fruite5.jpg'),
//   fruite6: require('../assets/images/Fruite6.jpg'),
//   fruite7: require('../assets/images/Fruite7.jpg'),
//   fruite8: require('../assets/images/Fruite8.jpg'),
//   fruite9: require('../assets/images/Fruite9.jpg'),
//   fruite10: require('../assets/images/Fruite10.jpg'),
//   group: require('../assets/images/Group.png'),
//   location: require('../assets/images/location.png'),
//   vectorPlus: require('../assets/images/Vector-plus.png'),
//   carrotImg: require('../assets/images/CarrotImg.png'),
//   carrotOrange: require('../assets/images/Carrot-Orange.png'),
//   facebook: require('../assets/images/Facebook.png'),
//   frame: require('../assets/images/Frame.png'),
//   vectorEye: require('../assets/images/Vector-Eye.png'),
//   flagImg: require('../assets/images/flagImg.png'),
//   groceryImg: require('../assets/images/groceryImg.jpg'),
//   illustration: require('../assets/images/illustration.png'),
//   welcomeImg: require('../assets/images/welcomeImg.jpg'),
//   google: require('../assets/images/Google.png'),
// };

// export type ImageMap = typeof Images;